-- Phase 18 conversation platform: the Lead Agent's durable substrate.
-- Conversations, turns, and a monotonic event stream (mirroring ca_run_events semantics so
-- resumable SSE ports directly), plus the three-layer memory system: owner profile, named
-- products (multi-project awareness), and episodic memories. Content is user-sensitive, so
-- every table is service-role only — the shell mediates all owner access.

create table public.ca_products (
  id uuid primary key default gen_random_uuid(),
  owner uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 120),
  summary text check (summary is null or char_length(summary) <= 2000),
  branding jsonb not null default '{}'::jsonb,
  state jsonb not null default '{}'::jsonb,
  repository_id uuid references public.ca_repositories(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (owner, name)
);

create table public.ca_conversations (
  id uuid primary key default gen_random_uuid(),
  owner uuid not null references auth.users(id) on delete cascade,
  title text check (title is null or char_length(title) <= 200),
  product_id uuid references public.ca_products(id) on delete set null,
  state text not null default 'idle'
    check (state in ('idle', 'thinking', 'waiting_user', 'archived')),
  last_activity_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ca_conversation_turns (
  id uuid primary key default gen_random_uuid(),
  owner uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid not null references public.ca_conversations(id) on delete cascade,
  sequence integer not null check (sequence > 0),
  role text not null check (role in ('user', 'lead', 'specialist', 'tool', 'system')),
  specialist text check (specialist is null or char_length(specialist) <= 60),
  content text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (conversation_id, sequence)
);

create table public.ca_conversation_events (
  id bigint generated by default as identity primary key,
  owner uuid not null references auth.users(id) on delete cascade,
  conversation_id uuid not null references public.ca_conversations(id) on delete cascade,
  sequence integer not null check (sequence > 0),
  type text not null check (char_length(type) between 1 and 100),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (conversation_id, sequence)
);

create table public.ca_owner_profile (
  owner uuid primary key references auth.users(id) on delete cascade,
  profile_encrypted text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ca_memories (
  id uuid primary key default gen_random_uuid(),
  owner uuid not null references auth.users(id) on delete cascade,
  product_id uuid references public.ca_products(id) on delete set null,
  kind text not null default 'fact' check (kind in ('preference', 'fact', 'episode')),
  content_encrypted text not null,
  created_at timestamptz not null default now()
);

create index ca_products_owner_idx on public.ca_products(owner, updated_at desc);
create index ca_conversations_owner_idx on public.ca_conversations(owner, last_activity_at desc);
create index ca_conversations_stale_idx on public.ca_conversations(state, updated_at)
  where state = 'thinking';
create index ca_conversation_turns_convo_idx on public.ca_conversation_turns(conversation_id, sequence);
create index ca_conversation_events_convo_idx on public.ca_conversation_events(conversation_id, sequence);
create index ca_memories_owner_idx on public.ca_memories(owner, created_at desc);
create index ca_memories_product_idx on public.ca_memories(product_id)
  where product_id is not null;

alter table public.ca_products enable row level security;
alter table public.ca_conversations enable row level security;
alter table public.ca_conversation_turns enable row level security;
alter table public.ca_conversation_events enable row level security;
alter table public.ca_owner_profile enable row level security;
alter table public.ca_memories enable row level security;

revoke all on table
  public.ca_products,
  public.ca_conversations,
  public.ca_conversation_turns,
  public.ca_conversation_events,
  public.ca_owner_profile,
  public.ca_memories
from public, anon, authenticated;

grant all privileges on table
  public.ca_products,
  public.ca_conversations,
  public.ca_conversation_turns,
  public.ca_conversation_events,
  public.ca_owner_profile,
  public.ca_memories
to service_role;

grant usage, select on sequence public.ca_conversation_events_id_seq to service_role;

create policy "ca_products_browser_deny" on public.ca_products
  as restrictive for all to anon, authenticated using (false) with check (false);
create policy "ca_conversations_browser_deny" on public.ca_conversations
  as restrictive for all to anon, authenticated using (false) with check (false);
create policy "ca_conversation_turns_browser_deny" on public.ca_conversation_turns
  as restrictive for all to anon, authenticated using (false) with check (false);
create policy "ca_conversation_events_browser_deny" on public.ca_conversation_events
  as restrictive for all to anon, authenticated using (false) with check (false);
create policy "ca_owner_profile_browser_deny" on public.ca_owner_profile
  as restrictive for all to anon, authenticated using (false) with check (false);
create policy "ca_memories_browser_deny" on public.ca_memories
  as restrictive for all to anon, authenticated using (false) with check (false);
