// Deterministic capability composition.
//
// These files are emitted by Thrallo before the first implementation-model turn. They instantiate
// proven runtime capabilities and are protected by the existing src/lib/capabilities write guard.
// The model consumes their interfaces and may implement only the declared configuration/custom
// extension modules.

import { CAPABILITIES } from "./capabilityRegistry.mjs";


export const CAPABILITY_COMPOSITION_VERSION = 1;
export const COMPOSED_ROOT = "src/lib/capabilities/composed";
export const CAPABILITY_CONFIGURATION_PATH = "src/extensions/capabilityConfiguration.js";

const unique = (values) => [...new Set((values || []).filter(Boolean))];
const quote = (value) => JSON.stringify(String(value));
const jsObject = (value) => JSON.stringify(value, null, 2);

const banner = (id) => `// Generated by Thrallo capability composer v${CAPABILITY_COMPOSITION_VERSION}: ${id}.\n`
  + "// Protected deterministic foundation. Import it; never edit or reimplement it.\n\n";

function wizardDefinitions(graph) {
  const wizard = (graph?.nodes || []).find((node) => node.id === "capability:wizard");
  if (!wizard) return [];
  return (graph?.journeys || []).filter((journey) => journey.requiredNodeIds.includes(wizard.id)).map((journey) => {
    const flows = journey.dataFlows || [];
    const stepIds = unique(flows.filter((flow) => /:(?:selection|input|review)(?::|$)/.test(flow.interactionId))
      .map((flow) => {
      const interaction = wizard.interactions.includes(flow.interactionId) ? flow.interactionId : null;
      return interaction ? String(interaction).split(":").slice(1, 3).join("-") : null;
      }));
    while (stepIds.length < 2) stepIds.push(`step-${stepIds.length + 1}`);
    return { id: journey.journeyId, steps: stepIds };
  });
}

function capabilityFiles(graph) {
  const nodes = new Map((graph?.nodes || []).map((node) => [node.id, node]));
  const files = {};
  const interfaces = [];
  const entities = nodes.get("capability:crud")?.entities || [];

  if (nodes.has("capability:crud")) {
    files[`${COMPOSED_ROOT}/crud.js`] = `${banner("crud")}import { makeEntityStore } from "../crud.js";

export const entityStores = Object.freeze({
${entities.map((entity) => `  ${quote(entity)}: makeEntityStore(${quote(entity)}),`).join("\n")}
});

export function entityStore(entityType) {
  const store = entityStores[String(entityType)];
  if (!store) throw new Error(\`No composed entity store for \${entityType}\`);
  return store;
}
`;
    interfaces.push({ module: `${COMPOSED_ROOT}/crud.js`, exports: ["entityStores", "entityStore"], owns: entities });
  }

  if (nodes.has("capability:session")) {
    const sessionExports = CAPABILITIES.session.interface;
    files[`${COMPOSED_ROOT}/session.js`] = `${banner("session")}export { ${sessionExports.join(", ")} } from "../session.js";
`;
    interfaces.push({ module: `${COMPOSED_ROOT}/session.js`, exports: [...sessionExports],
      asyncExports: [...sessionExports] });
  }

  if (nodes.has("capability:roles")) {
    files[`${COMPOSED_ROOT}/roles.js`] = `${banner("roles")}export { isOwner, requireOwner } from "../roles.js";
`;
    interfaces.push({ module: `${COMPOSED_ROOT}/roles.js`, exports: ["isOwner", "requireOwner"] });
  }

  const booking = nodes.get("capability:booking");
  if (booking) {
    const entity = booking.configuration?.entity || booking.entities[0] || "booking";
    files[`${COMPOSED_ROOT}/booking.js`] = `${banner("booking")}import { makeBookingSystem } from "../booking.js";
import { capabilityConfiguration } from "../../../extensions/capabilityConfiguration.js";

const slots = Array.isArray(capabilityConfiguration.booking?.slots)
  ? capabilityConfiguration.booking.slots : [];
export const bookingCapability = makeBookingSystem({ entity: ${quote(entity)}, slots });
`;
    interfaces.push({ module: `${COMPOSED_ROOT}/booking.js`, exports: ["bookingCapability"], owns: [entity], operations: booking.supportedOperations });
  }

  const wizard = nodes.get("capability:wizard");
  if (wizard) {
    const definitions = wizardDefinitions(graph);
    files[`${COMPOSED_ROOT}/wizard.js`] = `${banner("wizard")}import { makeWizardMachine } from "../wizard.js";
import { capabilityConfiguration } from "../../../extensions/capabilityConfiguration.js";

const definitions = ${jsObject(definitions)};
export const wizardMachines = Object.freeze(Object.fromEntries(definitions.map((definition) => {
  const extension = capabilityConfiguration.wizard?.[definition.id] || {};
  const allowed = {
    ...(extension.initialValues ? { initialValues: extension.initialValues } : {}),
    ...(typeof extension.validate === "function" ? { validate: extension.validate } : {}),
    ...(typeof extension.onConfirm === "function" ? { onConfirm: extension.onConfirm } : {}),
  };
  return [definition.id, makeWizardMachine({ id: definition.id, steps: definition.steps, ...allowed })];
})));

export function wizardFor(journeyId) {
  const machine = wizardMachines[String(journeyId)];
  if (!machine) throw new Error(\`No composed wizard for \${journeyId}\`);
  return machine;
}
`;
    interfaces.push({ module: `${COMPOSED_ROOT}/wizard.js`, exports: ["wizardMachines", "wizardFor"], owns: definitions.map((row) => row.id), operations: wizard.supportedOperations });
  }

  const contact = nodes.get("capability:contact");
  if (contact) {
    const entity = contact.configuration?.entity || contact.entities[0] || "contactMessage";
    files[`${COMPOSED_ROOT}/contact.js`] = `${banner("contact")}import { makeContactForm } from "../forms.js";
export const contactCapability = makeContactForm({ entity: ${quote(entity)} });
`;
    interfaces.push({ module: `${COMPOSED_ROOT}/contact.js`, exports: ["contactCapability"], owns: [entity], operations: contact.supportedOperations });
  }

  const newsletter = nodes.get("capability:newsletter");
  if (newsletter) {
    const entity = newsletter.configuration?.entity || newsletter.entities[0] || "newsletterSignup";
    files[`${COMPOSED_ROOT}/newsletter.js`] = `${banner("newsletter")}import { makeNewsletter } from "../forms.js";
export const newsletterCapability = makeNewsletter({ entity: ${quote(entity)} });
`;
    interfaces.push({ module: `${COMPOSED_ROOT}/newsletter.js`, exports: ["newsletterCapability"], owns: [entity], operations: newsletter.supportedOperations });
  }

  if (nodes.has("capability:interaction-primitives")) {
    files[`${COMPOSED_ROOT}/interaction-primitives.js`] = `${banner("interaction-primitives")}export {
  useCapabilityState, useCapabilityAction, useSemanticField, useSemanticSelection,
  useSemanticAction, useFlowAdvance, useStatusRegion,
} from "../react.js";
`;
    interfaces.push({ module: `${COMPOSED_ROOT}/interaction-primitives.js`, exports: [
      "useCapabilityState", "useCapabilityAction", "useSemanticField", "useSemanticSelection",
      "useSemanticAction", "useFlowAdvance", "useStatusRegion",
    ] });
  }

  const composedModules = interfaces.map((row) => row.module);
  files[`${COMPOSED_ROOT}/index.js`] = `${banner("public composition surface")}${composedModules
    .map((module) => `export * from "./${module.split("/").at(-1)}";`).join("\n")}
export { CAPABILITY_COMPOSITION } from "./manifest.js";
`;
  files[`${COMPOSED_ROOT}/manifest.js`] = `${banner("machine manifest")}export const CAPABILITY_COMPOSITION = Object.freeze(${jsObject({
    version: CAPABILITY_COMPOSITION_VERSION,
    graphVersion: graph?.version || 1,
    registryVersions: graph?.registryVersions || {},
    deterministicNodes: (graph?.nodes || []).filter((node) => node.type === "deterministic_capability")
      .map((node) => ({ id: node.id, capabilityId: node.capabilityId, version: node.version, module: node.compositionModule })),
    customBehavior: (graph?.nodes || []).filter((node) => node.type === "custom_behavior")
      .map((node) => ({ id: node.id, module: node.extension.module, requiredExports: node.extension.requiredExports })),
    interfaces,
  })});
`;
  return { files, interfaces };
}

export function capabilityCompositionPlan(graph) {
  const rendered = capabilityFiles(graph);
  const extensionPoints = (graph?.nodes || []).filter((node) => node.type === "custom_behavior")
    .map((node) => ({ id: node.id, ...node.extension, inputs: node.requiredInputs, outputs: node.outputs,
      stateOwnership: node.stateOwnership, persistenceSemantics: node.persistenceSemantics }));
  return {
    version: CAPABILITY_COMPOSITION_VERSION,
    graphVersion: graph?.version || 1,
    protectedRoot: COMPOSED_ROOT,
    protectedFiles: Object.keys(rendered.files).sort(),
    interfaces: rendered.interfaces,
    configurationModule: CAPABILITY_CONFIGURATION_PATH,
    extensionPoints,
  };
}

/** Apply or refresh the foundation. Existing model-owned extension configuration is preserved. */
export function composeCapabilityFoundation(tree, graph) {
  // Production Builder V2 starts from the full React/Vite scaffold. Some retained unit/legacy
  // baselines intentionally predate the capability runtime; do not emit adapters with dangling
  // imports into those trees. They remain on the migration-compatible path until refreshed from
  // the real scaffold, while every new production tree composes by default.
  const requiredRuntime = unique((graph?.nodes || [])
    .filter((node) => node.type === "deterministic_capability")
    .map((node) => CAPABILITIES[node.capabilityId]?.package));
  const missingRuntime = requiredRuntime.filter((path) => typeof tree?.[path] !== "string");
  if (missingRuntime.length) {
    return {
      tree: { ...(tree || {}) },
      plan: { ...capabilityCompositionPlan(graph), protectedFiles: [],
        skipped: "legacy_base_without_capability_runtime", missingRuntime },
    };
  }
  const rendered = capabilityFiles(graph);
  const next = { ...(tree || {}), ...rendered.files };
  if (typeof next[CAPABILITY_CONFIGURATION_PATH] !== "string") {
    next[CAPABILITY_CONFIGURATION_PATH] = `// Model-owned domain configuration for the protected capability composition.\n`
      + `// Configuration may supply visual/domain values and bounded hooks; it must not replace persistence.\n`
      + `export const capabilityConfiguration = Object.freeze({ booking: Object.freeze({ slots: [] }), wizard: Object.freeze({}) });\n`;
  }
  return { tree: next, plan: capabilityCompositionPlan(graph) };
}

export function capabilityCompositionBrief(graph, plan = capabilityCompositionPlan(graph)) {
  return [
    "DETERMINISTIC CAPABILITY COMPOSITION (already generated and protected; import, never recreate):",
    JSON.stringify({
      version: plan.version,
      interfaces: plan.interfaces,
      configurationModule: plan.configurationModule,
      extensionPoints: plan.extensionPoints,
    }, null, 2),
    "Known behavior is already implemented behind these interfaces. Build unique UI, layout, copy,",
    "domain configuration, integrations, and only the explicit custom_behavior extension modules.",
  ].join("\n");
}

export function validateCapabilityComposition(tree, graph, plan = capabilityCompositionPlan(graph)) {
  const problems = [];
  for (const path of plan.protectedFiles || []) {
    if (typeof tree?.[path] !== "string") problems.push(`composed capability module missing: ${path}`);
  }
  for (const extension of plan.extensionPoints || []) {
    const source = tree?.[extension.module];
    // New composed trees make custom behavior explicit and independently replaceable. Legacy
    // trees never reach this validator because they do not carry the composed manifest.
    if (typeof source !== "string") {
      problems.push(`custom behavior extension missing: ${extension.module}`);
      continue;
    }
    for (const name of extension.requiredExports || []) {
      if (!new RegExp(`\\bexport\\s+(?:async\\s+)?(?:function|const|let|var)\\s+${name}\\b`).test(source)
        && !new RegExp(`\\bexport\\s*\\{[^}]*\\b${name}\\b`).test(source)) {
        problems.push(`${extension.module} must export ${name}`);
      }
    }
  }
  return { ok: problems.length === 0, problems };
}
