// Build Orchestrator (finish plan WP-8; master plan Parts 2 §1, 4 and 5).
//
// One build = one FIRST-GREEN increment loop: contract → tiers/bindings/intents → assets
// (zero model) → CORE (the essential set only) → gates → essential journeys → GREEN
// snapshot + preview eligibility → secondary increments one at a time, each differentially
// verified, each rolled back alone on failure. The green core is never blocked by a
// secondary increment, and a crash resumes from the last green snapshot — nothing is
// rediscovered, no asset is ever re-searched.
//
// The two MODEL SEAMS (contractFn, patchesFn) are injected. WP-8 proves the whole loop
// with deterministic fakes at zero credits; WP-9 wires the real lanes behind its spend
// gate. Everything else is the real machinery: the real patch engine, the real stage
// gates via the verification facade, the real asset service, the real snapshot protocol.

import { indexTree } from "./indexer.mjs";
import { memoryGraph } from "./graphStore.mjs";
import { applyPatches } from "./patchEngine.mjs";
import { tierContract, bindCapabilities, imageIntents, previewEligibility } from "./contractTiering.mjs";
import { lintCapabilityUsage } from "./capabilityLint.mjs";
import {
  verifyStage, attributeFailures, planJourneyVerification, recordJourneyVerdicts, memoryVerificationCache,
} from "./verification.mjs";
import { createSnapshotStore } from "./snapshotStore.mjs";
import { serviceClient } from "../supabase.mjs";

// ── build persistence (bv2_builds twin pattern) ───────────────────────────────────────────────

export function memoryBuildStore() {
  const rows = new Map();
  let counter = 0;
  return {
    async create(row) { const id = `build-${++counter}`; rows.set(id, { id, ...row, states: [row.state] }); return id; },
    async update(id, patch) {
      const row = rows.get(id);
      Object.assign(row, patch);
      if (patch.state) row.states.push(patch.state);
    },
    async get(id) { return rows.get(id) || null; },
  };
}

export function supabaseBuildStore(client = serviceClient()) {
  return {
    async create(row) {
      const { data, error } = await client.from("bv2_builds").insert(row).select("id").single();
      if (error) throw new Error(`build create: ${error.message}`);
      return data.id;
    },
    async update(id, patch) {
      const { error } = await client.from("bv2_builds").update(patch).eq("id", id);
      if (error) throw new Error(`build update: ${error.message}`);
    },
    async get(id) {
      const { data } = await client.from("bv2_builds").select("*").eq("id", id).maybeSingle();
      return data || null;
    },
  };
}

// ── asset injection ───────────────────────────────────────────────────────────────────────────

/**
 * The resolved AssetRefs become CONSTANTS the model consumes (master plan Part 18) — it
 * never sees a provider, never chooses a URL. Keyed by slot; deterministic render order.
 */
export function renderAssetData(resolved) {
  const bySlot = {};
  for (const { slot, via, asset } of [...resolved].sort((a, b) => a.slot.localeCompare(b.slot))) {
    bySlot[slot] = via === "placeholder"
      ? { placeholder: true, css: asset.css, alt: asset.alt }
      : {
        alt_text: asset.alt_text, original_url: asset.original_url,
        optimised_url: asset.optimised_url || null,
        width: asset.width || null, height: asset.height || null,
        variants: asset.variants || {},
        attribution: asset.license?.attribution || null,
      };
  }
  return [
    "// GENERATED by the Asset Service — licensed, cached project imagery keyed by slot.",
    "// Render via src/lib/assets.js (imageProps/pictureSources); do not hardcode image URLs.",
    `export const ASSETS = ${JSON.stringify(bySlot, null, 2)};`,
    "export const ASSET_CREDITS = Object.values(ASSETS).map((asset) => asset.attribution).filter(Boolean);",
    "",
  ].join("\n");
}

/** Provider API terms are deterministic release constraints, not prompt advice. */
export function lintAssetAttribution(tree, assets = []) {
  const requiresPexelsCredit = assets.some(({ via, asset }) => (
    via !== "placeholder"
    && asset?.provider === "pexels"
    && asset?.license?.apiLinkRequired === true
  ));
  if (!requiresPexelsCredit) return { ok: true, problems: [] };

  // Metadata in assetData.js is not proof that the generated application renders it.
  const uiSource = Object.entries(tree || {})
    .filter(([path]) => path !== "src/lib/assetData.js" && /^src\/.+\.(?:js|jsx|ts|tsx)$/.test(path))
    .map(([, source]) => String(source))
    .join("\n");
  const problems = [];
  if (!/\bASSET_CREDITS\b/.test(uiSource)) problems.push("Pexels API compliance: render credits from ASSET_CREDITS in generated UI");
  if (!/https:\/\/(?:www\.)?pexels\.com(?:\/|[\"'])/.test(uiSource)) problems.push("Pexels API compliance: include a visible link to https://www.pexels.com");
  if (!/\bphotoUrl\b/.test(uiSource)) problems.push("Pexels API compliance: link each available photographer credit to photoUrl");
  return { ok: problems.length === 0, problems };
}

const problemSignature = (problems) => (problems || []).map((p) => String(p).slice(0, 120)).sort().join("|");

// ── the orchestrator ──────────────────────────────────────────────────────────────────────────

export function createOrchestrator({
  contractFn,                       // MODEL SEAM: async ({owner, projectId, request, profile}) → contract
  patchesFn,                        // MODEL SEAM: async ({step, contract, tiers, tree, assets, rejections, problems, journey}) → patches[]
  assetService,
  snapshotStore = createSnapshotStore(),
  buildStore = memoryBuildStore(),
  verificationCache = memoryVerificationCache(),
  verificationContext = {},          // safe release/runtime/config versions for cache identity
  journeysFn = null,                // browser layer: async ({tree, journeys, graph}) → {journeys:[{id,title,status,priority}]}
  backendProbeFn = null,            // D4 row check: async ({owner, projectId, contract, tiers}) → [{journeyId, detail}]
  maxJourneyRepairs = 2,            // V2-20 repair tier: targeted rounds against verified browser failures
  compile = async () => ({ ok: true }),
  baseTree,                         // () → scaffold tree (injected so tests pin the real REACT_VITE)
  baseline = null,                  // protected-path baseline for the stage gate
  extraGateOptions = {},            // e.g. { nodeModules, log } for live runs — merged into every gate call
  maxCoreAttempts = 3,              // 1 generation + 2 repairs (Part 4 stop rule)
  events = {},                      // durable composition hooks: contract, patches, snapshot
  log = () => {},
} = {}) {
  if (!contractFn || !patchesFn || !assetService || !baseTree) {
    throw new Error("orchestrator needs contractFn, patchesFn, assetService and baseTree");
  }

  const gateOptions = (contract, stepId, journeys, execution) => ({
    contract, stage: { id: stepId, journeys }, compile: (tree) => compile(tree, execution),
    ...(baseline ? { baseline } : {}), ...extraGateOptions,
  });

  const abortIfRequested = (signal) => {
    if (signal?.aborted) throw Object.assign(new Error("Builder V2 build cancelled."), {
      name: "AbortError", code: "cancelled",
    });
  };

  async function verifyJourneySet({ owner, projectId, buildId, contract, journeys, tree, snapshotId, signal }) {
    abortIfRequested(signal);
    const graph = memoryGraph(owner, projectId, indexTree(tree));
    const scoped = { ...contract, journeys };
    const plan = await planJourneyVerification({
      owner, projectId, contract: scoped, identityContract: contract, graph, cache: verificationCache,
      verificationContext,
    });
    let driven = { journeys: [] };
    if (plan.drive.length && journeysFn) {
      driven = await journeysFn({ owner, projectId, buildId, tree, journeys: plan.drive.map((d) => d.journey), graph, signal });
      abortIfRequested(signal);
      driven = { ...driven, journeys: attributeFailures(driven, graph, scoped) };
      await recordJourneyVerdicts({ owner, projectId, cache: verificationCache, plan, results: driven, snapshotId });
    }
    const platformDefects = driven.journeys.flatMap((j) => j.attributionDefect ? [j.attributionDefect] : []);
    for (const defect of platformDefects) log(JSON.stringify({ event: "bv2.platform_defect", ...defect }));
    const merged = [
      ...driven.journeys,
      ...plan.reused.map((r) => {
        const journey = journeys.find((j) => j.id === r.journeyId);
        return { id: r.journeyId, title: journey?.title, priority: journey?.priority, ...r.verdict, reused: true };
      }),
    ];
    return { journeys: merged, plan, platformDefects };
  }

  /**
   * Generate-and-gate one increment: up to maxCoreAttempts patch rounds, machine-taught
   * rejections fed straight back, the Part 4 stop rule on repeated identical failure.
   * Returns { ok, tree } or { ok:false, problems }.
   */
  async function buildIncrement({ step, owner, projectId, buildId, contract, tiers, tree, assets, journeys,
    editRequest = null, initialProblems = [], signal = null }) {
    let working = tree;
    let rejections = [];
    let problems = initialProblems;
    let lastSignature = null;
    for (let attempt = 1; attempt <= maxCoreAttempts; attempt += 1) {
      abortIfRequested(signal);
      const patches = await patchesFn({ step, owner, projectId, buildId, attempt, contract, tiers,
        tree: working, assets, rejections, problems, journey: journeys?.[0] || null, editRequest, signal });
      const applied = applyPatches(working, patches, { contract });
      const filesChanged = [...new Set([
        ...Object.keys(applied.tree).filter((path) => applied.tree[path] !== working[path]),
        ...Object.keys(working).filter((path) => !(path in applied.tree)),
      ])].sort();
      await events.patches?.({
        owner, projectId, buildId, step, attempt, patches,
        outcome: applied.rejected.length ? "rejected" : "applied",
        rejected: applied.rejected, filesChanged,
      });
      if (applied.rejected.length) {
        rejections = applied.rejected;
        log(`${step}: ${applied.rejected.length} patch op(s) rejected, feeding reasons back`);
        continue;
      }
      // No-op batches are rejected DETERMINISTICALLY, before a gate cycle is spent on them:
      // the first live run's model "replaced" a stub with its own identical content, twice.
      const changed = Object.keys(applied.tree).some((p) => applied.tree[p] !== working[p])
        || Object.keys(working).some((p) => !(p in applied.tree));
      if (!changed) {
        rejections = [{
          signature: "no-op",
          reason: "your batch left every file byte-identical — re-emitting current content is not implementation. "
            + "CREATE the required sections/pages as newFile entries (src/routes/…), register them in src/App.jsx, "
            + "and make every journey outcome visible as real UI text",
        }];
        log(`${step}: no-op batch rejected deterministically`);
        continue;
      }
      // D1 capability-usage lint — a call to a method the capability does not export is a
      // guaranteed runtime failure; caught HERE it costs a free round, not a browser cycle
      // (live run 3 lost its build to contactForm.submit vs submitContact).
      const usage = lintCapabilityUsage(applied.tree);
      if (!usage.ok) {
        rejections = usage.problems.map((reason) => ({ signature: "capability-usage", reason }));
        log(`${step}: ${usage.problems.length} capability-usage defect(s) rejected deterministically`);
        continue;
      }
      const assetCompliance = lintAssetAttribution(applied.tree, assets);
      if (!assetCompliance.ok) {
        rejections = assetCompliance.problems.map((reason) => ({ signature: "asset-attribution", reason }));
        log(`${step}: ${assetCompliance.problems.length} asset-attribution defect(s) rejected deterministically`);
        continue;
      }
      abortIfRequested(signal);
      const gate = await verifyStage(applied.tree, gateOptions(contract, step, journeys, {
        owner, projectId, buildId, step, attempt, signal,
      }));
      if (gate.ok) return { ok: true, tree: gate.tree };
      const gateProblems = gate.layers.d0d2.problems || [];
      const signature = problemSignature(gateProblems);
      if (signature === lastSignature) {
        return { ok: false, problems: gateProblems, reason: "the same defect survived a repair round (stop rule)" };
      }
      lastSignature = signature;
      problems = gateProblems;
      rejections = [];
      log(`${step}: gate failed (${gateProblems.length} problem(s)), repair attempt ${attempt}/${maxCoreAttempts}`);
    }
    return { ok: false, problems, reason: `no green tree within ${maxCoreAttempts} attempts` };
  }

  return {
    async runBuild({ owner, projectId, request, profile = "simple", budgetCredits = null, userCritical = [], signal = null }) {
      const buildId = await buildStore.create({
        owner, project_id: projectId, profile, request, state: "created",
        budget_credits: budgetCredits, started_at: new Date().toISOString(),
      });
      await events.buildCreated?.({ owner, projectId, buildId, mode: "build" });
      // Only REAL bv2_builds columns reach the store; everything else is return-value only
      // (the first live run died writing `problems` into the table). A store failure at
      // finish must never mask the build's actual outcome.
      const PERSISTED_FIELDS = ["error", "final_snapshot", "contract_id", "spent_credits"];
      const finish = async (state, extra = {}) => {
        const patch = { state, finished_at: new Date().toISOString() };
        for (const key of PERSISTED_FIELDS) if (key in extra) patch[key] = extra[key];
        try {
          await buildStore.update(buildId, patch);
        } catch (error) {
          log(`build row update failed (result unaffected): ${error.message}`);
        }
        return { buildId, state, ...extra };
      };

      // State transitions are telemetry — a transient store failure must never kill a
      // build that has already spent money.
      const setState = async (state) => {
        try { await buildStore.update(buildId, { state }); } catch (error) { log(`state update failed: ${error.message}`); }
      };

      try {
        abortIfRequested(signal);
        // 1. contract → tiers, capability bindings, image intents (deterministic after the call).
        await setState("contracting");
        const contract = await contractFn({ owner, projectId, buildId, request, profile, signal });
        const tiers = tierContract(contract, { userCritical });
        bindCapabilities(contract); // throws on an unknown/invalid binding — fail before spending anything
        const intents = imageIntents(contract);
        const persistedContract = await events.contract?.({ owner, projectId, buildId, contract, tiers,
          bindings: bindCapabilities(contract), intents });
        if (persistedContract?.id) {
          try { await buildStore.update(buildId, { contract_id: persistedContract.id }); }
          catch (error) { log(`contract id update failed: ${error.message}`); }
        }

        // 2. assets resolve BEFORE any generation, zero model turns, cache-first.
        await setState("assets");
        abortIfRequested(signal);
        const { resolved, providerCalls } = await assetService.resolveIntents(owner, projectId, intents);
        abortIfRequested(signal);
        log(`assets: ${resolved.length} slot(s), ${providerCalls} provider call(s)`);

        const journeysById = new Map((contract.journeys || []).map((j) => [j.id, j]));
        const essentialJourneys = tiers.essential.journeys.map((id) => journeysById.get(id)).filter(Boolean);
        const secondaryJourneys = tiers.secondary.journeys.map((id) => journeysById.get(id)).filter(Boolean);

        // 3. CORE: the essential set only.
        await setState("core");
        let tree = baseTree();
        tree["src/lib/assetData.js"] = renderAssetData(resolved);
        const core = await buildIncrement({
          step: "core", owner, projectId, buildId, contract, tiers, tree, assets: resolved,
          journeys: essentialJourneys, signal,
        });
        if (!core.ok) return finish("blocked", { error: core.reason, problems: core.problems });
        tree = core.tree;

        // 4. verify essential journeys (differential), then the C4 eligibility decision —
        //    with the V2-20 repair tier between them: a verified BROWSER failure earns up
        //    to maxJourneyRepairs targeted rounds, each briefed with the exact step
        //    evidence, each re-verified differentially (passing journeys reuse verdicts).
        await setState("verify_core");
        let coreVerdicts = await verifyJourneySet({ owner, projectId, buildId, contract,
          journeys: essentialJourneys, tree, snapshotId: null, signal });
        let backendRowFailures = backendProbeFn ? await backendProbeFn({
          owner, projectId, contract, tiers, journeyResults: coreVerdicts.journeys,
        }) : [];
        let eligibility = previewEligibility({ tiers, gates: { ok: true }, journeyResults: { journeys: coreVerdicts.journeys }, backendRowFailures });
        for (let round = 1; !eligibility.eligible && round <= maxJourneyRepairs; round += 1) {
          const evidence = [
            ...coreVerdicts.journeys.filter((j) => j.status === "fail").flatMap((j) => {
              const failedSteps = (j.steps || []).filter((s) => s.status === "fail");
              const journeyEvidence = failedSteps.length
                ? failedSteps.map((s) => `journey ${j.id} · step "${s.action}" FAILED in a real browser: ${s.detail || "expected outcome never appeared"}`)
                : [`journey ${j.id} FAILED in a real browser (no per-step evidence recorded)`];
              const attributionEvidence = j.attributionDefect
                ? [`platform defect ${j.attributionDefect.code}: journey ${j.id} has no owning module; bounded fallback files: ${(j.fallbackRefs || []).join(", ") || "none available"}`]
                : [];
              return [...journeyEvidence, ...attributionEvidence];
            }),
            ...backendRowFailures.map((f) => `backend row check failed (${f.journeyId}): ${f.detail}`),
          ];
          if (!evidence.length) break; // nothing actionable to brief — blocked below
          await setState(`repair:${round}`);
          log(`repair ${round}/${maxJourneyRepairs}: ${evidence.length} verified failure(s)`);
          const repair = await buildIncrement({
            step: "repair", owner, projectId, buildId, contract, tiers, tree, assets: resolved,
            journeys: essentialJourneys, initialProblems: evidence, signal,
          });
          if (!repair.ok) break;
          tree = repair.tree;
          coreVerdicts = await verifyJourneySet({ owner, projectId, buildId, contract,
            journeys: essentialJourneys, tree, snapshotId: null, signal });
          backendRowFailures = backendProbeFn ? await backendProbeFn({
            owner, projectId, contract, tiers, journeyResults: coreVerdicts.journeys,
          }) : [];
          eligibility = previewEligibility({ tiers, gates: { ok: true }, journeyResults: { journeys: coreVerdicts.journeys }, backendRowFailures });
        }
        if (!eligibility.eligible) return finish("blocked", {
          error: eligibility.failures.join("; "),
          platformDefects: coreVerdicts.platformDefects,
        });

        // 5. GREEN: atomic snapshot + pointer promotion. Preview may ship NOW (C4).
        const coreSnapshot = await snapshotStore.createSnapshot(owner, projectId, tree, {
          buildId, reason: "core", assetManifest: await assetService.assetManifestFor(owner, projectId),
        });
        await events.snapshot?.({ owner, projectId, buildId, snapshot: coreSnapshot, tree, reason: "core" });
        await snapshotStore.promote(owner, projectId, "green", coreSnapshot.id);
        try { await buildStore.update(buildId, { state: "green", final_snapshot: coreSnapshot.id }); } catch (error) { log(`green state update failed: ${error.message}`); }
        log(`core green: snapshot ${coreSnapshot.id}`);

        // 6. secondary increments — one at a time, each rolled back ALONE on failure.
        let lastGreen = coreSnapshot;
        const shipped = [];
        const pendingIncrements = [...eligibility.pendingIncrements];
        for (const journey of secondaryJourneys) {
          const step = `increment:${journey.id}`;
          await setState(step);
          const startTree = await snapshotStore.materialize(owner, lastGreen.id);
          const increment = await buildIncrement({
            step, owner, projectId, buildId, contract, tiers, tree: startTree, assets: resolved,
            journeys: [journey], signal,
          });
          let verdicts = null;
          if (increment.ok) {
            verdicts = await verifyJourneySet({ owner, projectId, buildId, contract,
              journeys: [journey], tree: increment.tree, snapshotId: lastGreen.id, signal });
          }
          const passed = increment.ok && !verdicts.journeys.some((j) => j.status === "fail");
          if (!passed) {
            // Rollback = simply not promoting; the green pointer still names lastGreen.
            pendingIncrements.push({ journeyId: journey.id, title: journey.title, reason: increment.ok ? "journey verification failed" : increment.reason });
            log(`${step}: failed — core stays green, increment reported as pending`);
            continue;
          }
          const snapshot = await snapshotStore.createSnapshot(owner, projectId, increment.tree, {
            buildId, parent: lastGreen.id, reason: step,
            assetManifest: await assetService.assetManifestFor(owner, projectId),
          });
          await events.snapshot?.({ owner, projectId, buildId, snapshot, tree: increment.tree, reason: step });
          await snapshotStore.promote(owner, projectId, "green", snapshot.id);
          lastGreen = snapshot;
          shipped.push(journey.id);
          log(`${step}: green (snapshot ${snapshot.id})`);
        }

        return finish("green", {
          final_snapshot: lastGreen.id,
          snapshotId: lastGreen.id,
          coreSnapshotId: coreSnapshot.id,
          shipped,
          pendingIncrements,
          providerCalls,
        });
      } catch (error) {
        return finish(error?.code === "cancelled" || error?.name === "AbortError" ? "cancelled" : "failed", { error: error.message });
      }
    },

    /**
     * Crash recovery: resume from the project's green pointer — the tree, index and cached
     * assets all come back without a single model call or provider search.
     */
    async resumeContext(owner, projectId) {
      const pointer = await snapshotStore.pointer(owner, projectId, "green");
      if (!pointer) return null;
      const tree = await snapshotStore.materialize(owner, pointer);
      return { snapshotId: pointer, tree, index: indexTree(tree) };
    },

    /**
     * The EDIT path (finish plan WP-10 / V2-18): adopt the green snapshot → patch → gate →
     * DIFFERENTIAL journey verification (unchanged owners reuse their cached PASS verdicts;
     * only journeys whose owning modules changed are re-driven) → new snapshot promoted
     * atomically. A failed edit promotes nothing — the prior green keeps serving. No
     * contract call, no asset search: everything persistent is simply resumed.
     */
    async runEdit({ owner, projectId, request, contract, userCritical = [], signal = null }) {
      const buildId = await buildStore.create({
        owner, project_id: projectId, profile: "edit", request, state: "created",
        started_at: new Date().toISOString(),
      });
      await events.buildCreated?.({ owner, projectId, buildId, mode: "edit" });
      const finish = async (state, extra = {}) => {
        const patch = { state, finished_at: new Date().toISOString() };
        for (const key of ["error", "final_snapshot"]) if (key in extra) patch[key] = extra[key];
        try { await buildStore.update(buildId, patch); } catch (error) { log(`edit row update failed (result unaffected): ${error.message}`); }
        return { buildId, state, ...extra };
      };
      const setState = async (state) => {
        try { await buildStore.update(buildId, { state }); } catch (error) { log(`state update failed: ${error.message}`); }
      };

      try {
        abortIfRequested(signal);
        const ctx = await this.resumeContext(owner, projectId);
        if (!ctx) return finish("blocked", { error: "no green snapshot to edit — run a build first" });
        // Capability/backend modules are platform-owned and upgrade on iterate. Legacy adoption
        // gains new reliable behaviours without asking a model to recreate protected code.
        const currentPlatform = baseTree();
        for (const [path, source] of Object.entries(currentPlatform)) {
          if (/^src\/lib\/(?:capabilities\/|backend\/|visitorSession\.js$|assets\.js$)/.test(path)) {
            ctx.tree[path] = source;
          }
        }
        const tiers = tierContract(contract, { userCritical });
        const journeys = contract.journeys || [];

        await setState("editing");
        const edit = await buildIncrement({
          step: "edit", owner, projectId, buildId, contract, tiers, tree: ctx.tree, assets: [],
          journeys, editRequest: request, signal,
        });
        if (!edit.ok) return finish("blocked", { error: edit.reason, problems: edit.problems });

        // Differential verification over EVERY contract journey: the cache decides what to
        // actually drive. Unchanged owners reuse; changed owners (and prior fails) re-drive.
        await setState("verify_edit");
        const verdicts = await verifyJourneySet({ owner, projectId, buildId, contract,
          journeys, tree: edit.tree, snapshotId: ctx.snapshotId, signal });
        const eligibility = previewEligibility({ tiers, gates: { ok: true }, journeyResults: { journeys: verdicts.journeys } });
        if (!eligibility.eligible) return finish("blocked", {
          error: eligibility.failures.join("; "),
          platformDefects: verdicts.platformDefects,
        });

        const snapshot = await snapshotStore.createSnapshot(owner, projectId, edit.tree, {
          buildId, parent: ctx.snapshotId, reason: "edit",
          assetManifest: await assetService.assetManifestFor(owner, projectId),
        });
        await events.snapshot?.({ owner, projectId, buildId, snapshot, tree: edit.tree, reason: "edit" });
        await events.knowledge?.({
          owner, projectId, buildId, kind: "decision", key: `edit:${buildId}`,
          value: { text: request, verifiedSnapshot: snapshot.id },
        });
        await snapshotStore.promote(owner, projectId, "green", snapshot.id);
        log(`edit green: snapshot ${snapshot.id} (drove ${verdicts.plan.drive.length}, reused ${verdicts.plan.reused.length})`);
        return finish("green", {
          final_snapshot: snapshot.id,
          snapshotId: snapshot.id,
          parentSnapshotId: ctx.snapshotId,
          drove: verdicts.plan.drive.map((d) => d.journey.id),
          reused: verdicts.plan.reused.map((r) => r.journeyId),
          pendingIncrements: eligibility.pendingIncrements,
        });
      } catch (error) {
        return finish(error?.code === "cancelled" || error?.name === "AbortError" ? "cancelled" : "failed", { error: error.message });
      }
    },
  };
}
