// Build Orchestrator (finish plan WP-8; master plan Parts 2 §1, 4 and 5).
//
// One build = one FIRST-GREEN increment loop: contract → tiers/bindings/intents → assets
// (zero model) → CORE (the essential set only) → gates → essential journeys → GREEN
// snapshot + preview eligibility → secondary increments one at a time, each differentially
// verified, each rolled back alone on failure. The green core is never blocked by a
// secondary increment, and a crash resumes from the last green snapshot — nothing is
// rediscovered, no asset is ever re-searched.
//
// The two MODEL SEAMS (contractFn, patchesFn) are injected. WP-8 proves the whole loop
// with deterministic fakes at zero credits; WP-9 wires the real lanes behind its spend
// gate. Everything else is the real machinery: the real patch engine, the real stage
// gates via the verification facade, the real asset service, the real snapshot protocol.

import { indexTree } from "./indexerV0.mjs";
import { memoryGraph } from "./graphStore.mjs";
import { applyPatches } from "./patchEngine.mjs";
import { tierContract, bindCapabilities, imageIntents, previewEligibility } from "./contractTiering.mjs";
import {
  verifyStage, planJourneyVerification, recordJourneyVerdicts, memoryVerificationCache,
} from "./verification.mjs";
import { createSnapshotStore } from "./snapshotStore.mjs";
import { serviceClient } from "../supabase.mjs";

// ── build persistence (bv2_builds twin pattern) ───────────────────────────────────────────────

export function memoryBuildStore() {
  const rows = new Map();
  let counter = 0;
  return {
    async create(row) { const id = `build-${++counter}`; rows.set(id, { id, ...row, states: [row.state] }); return id; },
    async update(id, patch) {
      const row = rows.get(id);
      Object.assign(row, patch);
      if (patch.state) row.states.push(patch.state);
    },
    async get(id) { return rows.get(id) || null; },
  };
}

export function supabaseBuildStore(client = serviceClient()) {
  return {
    async create(row) {
      const { data, error } = await client.from("bv2_builds").insert(row).select("id").single();
      if (error) throw new Error(`build create: ${error.message}`);
      return data.id;
    },
    async update(id, patch) {
      const { error } = await client.from("bv2_builds").update(patch).eq("id", id);
      if (error) throw new Error(`build update: ${error.message}`);
    },
    async get(id) {
      const { data } = await client.from("bv2_builds").select("*").eq("id", id).maybeSingle();
      return data || null;
    },
  };
}

// ── asset injection ───────────────────────────────────────────────────────────────────────────

/**
 * The resolved AssetRefs become CONSTANTS the model consumes (master plan Part 18) — it
 * never sees a provider, never chooses a URL. Keyed by slot; deterministic render order.
 */
export function renderAssetData(resolved) {
  const bySlot = {};
  for (const { slot, via, asset } of [...resolved].sort((a, b) => a.slot.localeCompare(b.slot))) {
    bySlot[slot] = via === "placeholder"
      ? { placeholder: true, css: asset.css, alt: asset.alt }
      : {
        alt_text: asset.alt_text, original_url: asset.original_url,
        optimised_url: asset.optimised_url || null,
        width: asset.width || null, height: asset.height || null,
        variants: asset.variants || {},
      };
  }
  return [
    "// GENERATED by the Asset Service — licensed, cached project imagery keyed by slot.",
    "// Render via src/lib/assets.js (imageProps/pictureSources); do not hardcode image URLs.",
    `export const ASSETS = ${JSON.stringify(bySlot, null, 2)};`,
    "",
  ].join("\n");
}

const problemSignature = (problems) => (problems || []).map((p) => String(p).slice(0, 120)).sort().join("|");

// ── the orchestrator ──────────────────────────────────────────────────────────────────────────

export function createOrchestrator({
  contractFn,                       // MODEL SEAM: async ({owner, projectId, request, profile}) → contract
  patchesFn,                        // MODEL SEAM: async ({step, contract, tiers, tree, assets, rejections, problems, journey}) → patches[]
  assetService,
  snapshotStore = createSnapshotStore(),
  buildStore = memoryBuildStore(),
  verificationCache = memoryVerificationCache(),
  journeysFn = null,                // browser layer: async ({tree, journeys, graph}) → {journeys:[{id,title,status,priority}]}
  compile = async () => ({ ok: true }),
  baseTree,                         // () → scaffold tree (injected so tests pin the real REACT_VITE)
  baseline = null,                  // protected-path baseline for the stage gate
  extraGateOptions = {},            // e.g. { nodeModules, log } for live runs — merged into every gate call
  maxCoreAttempts = 3,              // 1 generation + 2 repairs (Part 4 stop rule)
  log = () => {},
} = {}) {
  if (!contractFn || !patchesFn || !assetService || !baseTree) {
    throw new Error("orchestrator needs contractFn, patchesFn, assetService and baseTree");
  }

  const gateOptions = (contract, stepId, journeys) => ({
    contract, stage: { id: stepId, journeys }, compile, ...(baseline ? { baseline } : {}), ...extraGateOptions,
  });

  async function verifyJourneySet({ owner, projectId, contract, journeys, tree, snapshotId }) {
    const graph = memoryGraph(owner, projectId, indexTree(tree));
    const scoped = { ...contract, journeys };
    const plan = await planJourneyVerification({ owner, projectId, contract: scoped, graph, cache: verificationCache });
    let driven = { journeys: [] };
    if (plan.drive.length && journeysFn) {
      driven = await journeysFn({ tree, journeys: plan.drive.map((d) => d.journey), graph });
      await recordJourneyVerdicts({ owner, projectId, cache: verificationCache, plan, results: driven, snapshotId });
    }
    const merged = [
      ...driven.journeys,
      ...plan.reused.map((r) => {
        const journey = journeys.find((j) => j.id === r.journeyId);
        return { id: r.journeyId, title: journey?.title, priority: journey?.priority, ...r.verdict, reused: true };
      }),
    ];
    return { journeys: merged, plan };
  }

  /**
   * Generate-and-gate one increment: up to maxCoreAttempts patch rounds, machine-taught
   * rejections fed straight back, the Part 4 stop rule on repeated identical failure.
   * Returns { ok, tree } or { ok:false, problems }.
   */
  async function buildIncrement({ step, owner, contract, tiers, tree, assets, journeys }) {
    let working = tree;
    let rejections = [];
    let problems = [];
    let lastSignature = null;
    for (let attempt = 1; attempt <= maxCoreAttempts; attempt += 1) {
      const patches = await patchesFn({ step, owner, contract, tiers, tree: working, assets, rejections, problems, journey: journeys?.[0] || null });
      const applied = applyPatches(working, patches, { contract });
      if (applied.rejected.length) {
        rejections = applied.rejected;
        log(`${step}: ${applied.rejected.length} patch op(s) rejected, feeding reasons back`);
        continue;
      }
      // No-op batches are rejected DETERMINISTICALLY, before a gate cycle is spent on them:
      // the first live run's model "replaced" a stub with its own identical content, twice.
      const changed = Object.keys(applied.tree).some((p) => applied.tree[p] !== working[p])
        || Object.keys(working).some((p) => !(p in applied.tree));
      if (!changed) {
        rejections = [{
          signature: "no-op",
          reason: "your batch left every file byte-identical — re-emitting current content is not implementation. "
            + "CREATE the required sections/pages as newFile entries (src/routes/…), register them in src/App.jsx, "
            + "and make every journey outcome visible as real UI text",
        }];
        log(`${step}: no-op batch rejected deterministically`);
        continue;
      }
      const gate = await verifyStage(applied.tree, gateOptions(contract, step, journeys));
      if (gate.ok) return { ok: true, tree: gate.tree };
      const gateProblems = gate.layers.d0d2.problems || [];
      const signature = problemSignature(gateProblems);
      if (signature === lastSignature) {
        return { ok: false, problems: gateProblems, reason: "the same defect survived a repair round (stop rule)" };
      }
      lastSignature = signature;
      problems = gateProblems;
      rejections = [];
      log(`${step}: gate failed (${gateProblems.length} problem(s)), repair attempt ${attempt}/${maxCoreAttempts}`);
    }
    return { ok: false, problems, reason: `no green tree within ${maxCoreAttempts} attempts` };
  }

  return {
    async runBuild({ owner, projectId, request, profile = "simple", budgetCredits = null, userCritical = [] }) {
      const buildId = await buildStore.create({
        owner, project_id: projectId, profile, request, state: "created",
        budget_credits: budgetCredits, started_at: new Date().toISOString(),
      });
      // Only REAL bv2_builds columns reach the store; everything else is return-value only
      // (the first live run died writing `problems` into the table). A store failure at
      // finish must never mask the build's actual outcome.
      const PERSISTED_FIELDS = ["error", "final_snapshot", "contract_id", "spent_credits"];
      const finish = async (state, extra = {}) => {
        const patch = { state, finished_at: new Date().toISOString() };
        for (const key of PERSISTED_FIELDS) if (key in extra) patch[key] = extra[key];
        try {
          await buildStore.update(buildId, patch);
        } catch (error) {
          log(`build row update failed (result unaffected): ${error.message}`);
        }
        return { buildId, state, ...extra };
      };

      // State transitions are telemetry — a transient store failure must never kill a
      // build that has already spent money.
      const setState = async (state) => {
        try { await buildStore.update(buildId, { state }); } catch (error) { log(`state update failed: ${error.message}`); }
      };

      try {
        // 1. contract → tiers, capability bindings, image intents (deterministic after the call).
        await setState("contracting");
        const contract = await contractFn({ owner, projectId, request, profile });
        const tiers = tierContract(contract, { userCritical });
        bindCapabilities(contract); // throws on an unknown/invalid binding — fail before spending anything
        const intents = imageIntents(contract);

        // 2. assets resolve BEFORE any generation, zero model turns, cache-first.
        await setState("assets");
        const { resolved, providerCalls } = await assetService.resolveIntents(owner, projectId, intents);
        log(`assets: ${resolved.length} slot(s), ${providerCalls} provider call(s)`);

        const journeysById = new Map((contract.journeys || []).map((j) => [j.id, j]));
        const essentialJourneys = tiers.essential.journeys.map((id) => journeysById.get(id)).filter(Boolean);
        const secondaryJourneys = tiers.secondary.journeys.map((id) => journeysById.get(id)).filter(Boolean);

        // 3. CORE: the essential set only.
        await setState("core");
        let tree = baseTree();
        tree["src/lib/assetData.js"] = renderAssetData(resolved);
        const core = await buildIncrement({
          step: "core", owner, contract, tiers, tree, assets: resolved, journeys: essentialJourneys,
        });
        if (!core.ok) return finish("blocked", { error: core.reason, problems: core.problems });
        tree = core.tree;

        // 4. verify essential journeys (differential), then the C4 eligibility decision.
        await setState("verify_core");
        const coreVerdicts = await verifyJourneySet({ owner, projectId, contract, journeys: essentialJourneys, tree, snapshotId: null });
        const eligibility = previewEligibility({ tiers, gates: { ok: true }, journeyResults: { journeys: coreVerdicts.journeys } });
        if (!eligibility.eligible) return finish("blocked", { error: eligibility.failures.join("; ") });

        // 5. GREEN: atomic snapshot + pointer promotion. Preview may ship NOW (C4).
        const coreSnapshot = await snapshotStore.createSnapshot(owner, projectId, tree, {
          buildId, reason: "core", assetManifest: await assetService.assetManifestFor(owner, projectId),
        });
        await snapshotStore.promote(owner, projectId, "green", coreSnapshot.id);
        try { await buildStore.update(buildId, { state: "green", final_snapshot: coreSnapshot.id }); } catch (error) { log(`green state update failed: ${error.message}`); }
        log(`core green: snapshot ${coreSnapshot.id}`);

        // 6. secondary increments — one at a time, each rolled back ALONE on failure.
        let lastGreen = coreSnapshot;
        const shipped = [];
        const pendingIncrements = [...eligibility.pendingIncrements];
        for (const journey of secondaryJourneys) {
          const step = `increment:${journey.id}`;
          await setState(step);
          const startTree = await snapshotStore.materialize(owner, lastGreen.id);
          const increment = await buildIncrement({
            step, owner, contract, tiers, tree: startTree, assets: resolved, journeys: [journey],
          });
          let verdicts = null;
          if (increment.ok) {
            verdicts = await verifyJourneySet({ owner, projectId, contract, journeys: [journey], tree: increment.tree, snapshotId: lastGreen.id });
          }
          const passed = increment.ok && !verdicts.journeys.some((j) => j.status === "fail");
          if (!passed) {
            // Rollback = simply not promoting; the green pointer still names lastGreen.
            pendingIncrements.push({ journeyId: journey.id, title: journey.title, reason: increment.ok ? "journey verification failed" : increment.reason });
            log(`${step}: failed — core stays green, increment reported as pending`);
            continue;
          }
          const snapshot = await snapshotStore.createSnapshot(owner, projectId, increment.tree, {
            buildId, parent: lastGreen.id, reason: step,
            assetManifest: await assetService.assetManifestFor(owner, projectId),
          });
          await snapshotStore.promote(owner, projectId, "green", snapshot.id);
          lastGreen = snapshot;
          shipped.push(journey.id);
          log(`${step}: green (snapshot ${snapshot.id})`);
        }

        return finish("green", {
          final_snapshot: lastGreen.id,
          snapshotId: lastGreen.id,
          coreSnapshotId: coreSnapshot.id,
          shipped,
          pendingIncrements,
          providerCalls,
        });
      } catch (error) {
        return finish("failed", { error: error.message });
      }
    },

    /**
     * Crash recovery: resume from the project's green pointer — the tree, index and cached
     * assets all come back without a single model call or provider search.
     */
    async resumeContext(owner, projectId) {
      const pointer = await snapshotStore.pointer(owner, projectId, "green");
      if (!pointer) return null;
      const tree = await snapshotStore.materialize(owner, pointer);
      return { snapshotId: pointer, tree, index: indexTree(tree) };
    },
  };
}
