// Deterministic universal scaffold composer.
//
// The composer owns mounting and common structural mechanics. Model-owned screen slots are
// created before generation and mounted immediately; the model may replace their presentation
// and connect declared capability/extension interfaces, but cannot replace the router/shell.

import { createHash } from "node:crypto";

import { scaffoldEntry } from "./scaffoldRegistry.mjs";

export const SCAFFOLD_COMPOSITION_VERSION = 1;
export const SCAFFOLD_COMPOSED_ROOT = "src/lib/scaffolds/composed";
export const SCAFFOLD_APP_PATH = `${SCAFFOLD_COMPOSED_ROOT}/ScaffoldApp.jsx`;
export const SCAFFOLD_PRIMITIVES_PATH = `${SCAFFOLD_COMPOSED_ROOT}/primitives.jsx`;
export const SCAFFOLD_MANIFEST_PATH = `${SCAFFOLD_COMPOSED_ROOT}/manifest.js`;
export const SCAFFOLD_ENTRY_PATH = "src/App.jsx";
export const SCREEN_SLOT_MARKER = "Thrallo scaffold screen slot";

const digest = (value) => createHash("sha256").update(String(value)).digest("hex");
const unique = (values) => [...new Set((values || []).filter(Boolean))];
const js = (value) => JSON.stringify(value, null, 2);
const quote = (value) => JSON.stringify(String(value));
const banner = (name) => `// Generated by Thrallo scaffold composer v${SCAFFOLD_COMPOSITION_VERSION}: ${name}.\n`
  + "// Protected deterministic application structure. Import it; never edit it.\n\n";

function importName(screen, index) {
  return `MountedScreen${index + 1}_${String(screen.screenId || "screen").replace(/[^a-zA-Z0-9_$]/g, "_")}`;
}

function primitivesSource() {
  return `${banner("generic structural primitives")}import React, { useCallback, useEffect, useMemo, useState } from "react";

export function useFormState(initialValues = {}) {
  const [values, setValues] = useState(() => ({ ...initialValues }));
  const setField = useCallback((name, value) => setValues((current) => ({ ...current, [name]: value })), []);
  const reset = useCallback((next = initialValues) => setValues({ ...next }), [initialValues]);
  return { values, setValues, setField, reset };
}
export function useWorkflowState({ steps = [], initialValues = {} } = {}) {
  const form = useFormState(initialValues);
  const [stepIndex, setStepIndex] = useState(0);
  const [result, setResult] = useState(null);
  const lastIndex = Math.max(0, steps.length - 1);
  const next = useCallback(() => setStepIndex((index) => Math.min(lastIndex, index + 1)), [lastIndex]);
  const back = useCallback(() => setStepIndex((index) => Math.max(0, index - 1)), []);
  const goTo = useCallback((index) => setStepIndex(Math.max(0, Math.min(lastIndex, Number(index) || 0))), [lastIndex]);
  const confirm = useCallback((value) => { setResult(value); setStepIndex(lastIndex); return value; }, [lastIndex]);
  return { ...form, steps, stepIndex, step: steps[stepIndex] || null, isFirst: stepIndex === 0,
    isLast: stepIndex === lastIndex, next, back, goTo, result, confirm };
}
export function useResourceState(store, { autoLoad = true } = {}) {
  const [rows, setRows] = useState([]);
  const [selected, setSelected] = useState(null);
  const [status, setStatus] = useState(autoLoad ? "loading" : "idle");
  const [error, setError] = useState(null);
  const run = useCallback(async (operation) => {
    setStatus("loading"); setError(null);
    try { const value = await operation(); setStatus("ready"); return value; }
    catch (cause) { setError(cause); setStatus("error"); throw cause; }
  }, []);
  const reload = useCallback(async () => {
    const value = await run(() => store.list()); setRows(value || []); return value || [];
  }, [run, store]);
  useEffect(() => { if (autoLoad) void reload(); }, [autoLoad, reload]);
  const create = useCallback(async (values) => {
    const value = await run(() => store.create(values)); setRows((current) => [...current, value]); setSelected(value); return value;
  }, [run, store]);
  const update = useCallback(async (id, values) => {
    const value = await run(() => store.update(id, values));
    setRows((current) => current.map((row) => row.id === id ? value : row));
    setSelected((current) => current?.id === id ? value : current); return value;
  }, [run, store]);
  const remove = useCallback(async (id) => {
    await run(() => store.remove(id)); setRows((current) => current.filter((row) => row.id !== id));
    setSelected((current) => current?.id === id ? null : current);
  }, [run, store]);
  return { rows, selected, select: setSelected, status, error, reload, create, update, remove };
}
export function useCatalogueState(items = [], searchableText = (item) => String(item ?? "")) {
  const [query, setQuery] = useState(""); const [selected, select] = useState(null);
  const visibleItems = useMemo(() => { const needle = query.trim().toLowerCase(); return needle
    ? items.filter((item) => searchableText(item).toLowerCase().includes(needle)) : items; }, [items, query, searchableText]);
  return { query, setQuery, selected, select, visibleItems };
}
export function useProjectWorkspace(store, initialDraft = {}) {
  const resource = useResourceState(store);
  const [draft, setDraft] = useState(() => ({ ...initialDraft }));
  const [activeProject, setActiveProject] = useState(null);
  const open = useCallback((project) => { setActiveProject(project); setDraft({ ...(project || initialDraft) }); }, [initialDraft]);
  const save = useCallback(async (overrides = {}) => {
    const values = { ...draft, ...overrides };
    const saved = activeProject?.id ? await resource.update(activeProject.id, values) : await resource.create(values);
    setActiveProject(saved); setDraft({ ...saved }); return saved;
  }, [activeProject, draft, resource]);
  return { ...resource, draft, setDraft, activeProject, open, save };
}
export function useCanvasState(initialObjects = []) {
  const [objects, setObjects] = useState(() => [...initialObjects]); const [selectedId, select] = useState(null);
  const updateObject = useCallback((id, patch) => setObjects((current) => current.map((object) => (
    object.id === id ? { ...object, ...(typeof patch === "function" ? patch(object) : patch) } : object))), []);
  return { objects, setObjects, selectedId, select, selected: objects.find((object) => object.id === selectedId) || null, updateObject };
}

export function AppShell({ navigation = null, children, className = "" }) {
  return <div data-scaffold="app_shell" className={className}>{navigation}{children}</div>;
}
export function NavigationShell({ children, className = "" }) {
  return <nav data-scaffold="content_navigation" aria-label="Primary" className={className}>{children}</nav>;
}
export function ResourceShell({ list = null, detail = null, form = null, actions = null, className = "" }) {
  return <section data-scaffold="crud_resource" className={className}>{list}{detail}{form}{actions}</section>;
}
export function CatalogueDetailShell({ catalogue = null, detail = null, className = "" }) {
  return <section data-scaffold="catalogue_detail" className={className}>{catalogue}{detail}</section>;
}
export function DashboardShell({ summary = null, content = null, className = "" }) {
  return <section data-scaffold="dashboard" className={className}>{summary}{content}</section>;
}
export function WorkflowShell({ progress = null, step = null, review = null, confirmation = null, className = "" }) {
  return <section data-scaffold="workflow" className={className}>{progress}{step}{review}{confirmation}</section>;
}
export function ProjectWorkspaceShell({ toolbar = null, projects = null, workspace = null, className = "" }) {
  return <section data-scaffold="project_workspace" className={className}>{toolbar}{projects}{workspace}</section>;
}
export function CanvasEditorShell({ toolbar = null, surface = null, inspector = null, className = "" }) {
  return <section data-scaffold="canvas_editor" className={className}>{toolbar}{surface}{inspector}</section>;
}
export function SchedulingShell({ availability = null, selection = null, status = null, className = "" }) {
  return <section data-scaffold="scheduling" className={className}>{availability}{selection}{status}</section>;
}
export function AuthAccountShell({ form = null, account = null, status = null, className = "" }) {
  return <section data-scaffold="auth_account" className={className}>{form}{account}{status}</section>;
}
export function AdminManagementShell({ navigation = null, content = null, className = "" }) {
  return <section data-scaffold="admin_management" className={className}>{navigation}{content}</section>;
}
export function ExportOutputShell({ preview = null, action = null, status = null, className = "" }) {
  return <section data-scaffold="export_output" className={className}>{preview}{action}{status}</section>;
}
export function ScaffoldLoadingBoundary({ label = "Loading" }) {
  return <div role="status" aria-live="polite" data-scaffold-boundary="loading">{label}</div>;
}
export class ScaffoldErrorBoundary extends React.Component {
  constructor(props) { super(props); this.state = { error: null }; }
  static getDerivedStateFromError(error) { return { error }; }
  componentDidCatch(error) { console.error("scaffold screen render failed", error); }
  render() {
    if (this.state.error) return <main role="alert" data-scaffold-boundary="error"><h1>This screen could not load</h1><p>Please try again.</p></main>;
    return this.props.children;
  }
}
`;
}

function scaffoldAppSource(graph) {
  const screens = graph?.screens || [];
  const imports = screens.map((screen, index) => `import ${importName(screen, index)} from ${quote(`../../../${screen.module.replace(/^src\//, "").replace(/\.(?:jsx?|tsx?)$/, "")}.jsx`)};`);
  // The protected module lives at src/lib/scaffolds/composed, so ../../../screens/... is stable.
  const routes = screens.map((screen, index) => `  { path: ${quote(screen.routePath)}, name: ${quote(screen.routeName)}, screenId: ${quote(screen.screenId)}, Screen: ${importName(screen, index)} },`);
  return `${banner("mounted route authority")}import React, { Suspense, useEffect, useState } from "react";
import { AppShell, NavigationShell, ScaffoldErrorBoundary, ScaffoldLoadingBoundary } from "./primitives.jsx";
${imports.join("\n")}

export const SCAFFOLD_ROUTES = Object.freeze([
${routes.join("\n")}
]);

function normalizePath(value) {
  const path = String(value || "/").split(/[?#]/)[0] || "/";
  return path.length > 1 ? path.replace(/\\/+$/, "") : path;
}
function routeMatches(pattern, actual) {
  const wanted = normalizePath(pattern).split("/").filter(Boolean);
  const seen = normalizePath(actual).split("/").filter(Boolean);
  if (wanted.length !== seen.length) return false;
  return wanted.every((part, index) => part.startsWith(":") || part === "*" || part === seen[index]);
}
function currentPath() { return normalizePath(globalThis.location?.pathname || "/"); }
function go(path, setPath) {
  const target = normalizePath(path);
  if (target === currentPath()) return;
  globalThis.history?.pushState?.({}, "", target);
  setPath(target);
}

export function ScaffoldNavigation({ path, setPath }) {
  if (SCAFFOLD_ROUTES.length < 2) return null;
  return <NavigationShell>{SCAFFOLD_ROUTES.map((route) => <a key={route.path} href={route.path}
    aria-current={routeMatches(route.path, path) ? "page" : undefined}
    onClick={(event) => { if (!event.metaKey && !event.ctrlKey && !event.shiftKey && event.button === 0) { event.preventDefault(); go(route.path, setPath); } }}>
    {route.name}</a>)}</NavigationShell>;
}

export default function ScaffoldApp() {
  const [path, setPath] = useState(currentPath);
  useEffect(() => { const onPop = () => setPath(currentPath()); globalThis.addEventListener?.("popstate", onPop); return () => globalThis.removeEventListener?.("popstate", onPop); }, []);
  const route = SCAFFOLD_ROUTES.find((candidate) => routeMatches(candidate.path, path)) || SCAFFOLD_ROUTES[0];
  const Screen = route?.Screen;
  return <ScaffoldErrorBoundary><AppShell navigation={<ScaffoldNavigation path={path} setPath={setPath} />}>
    <Suspense fallback={<ScaffoldLoadingBoundary />}><main data-scaffold-screen={route?.screenId || "missing"} data-scaffold-route={route?.path || path}>
      {Screen ? <Screen /> : <div role="alert">No mounted screen is available.</div>}
    </main></Suspense>
  </AppShell></ScaffoldErrorBoundary>;
}
`;
}

function screenSlotSource(screen, graph) {
  const owner = (graph?.journeyOwnership || []).filter((row) => row.screenId === screen.screenId);
  const families = unique(owner.flatMap((row) => row.scaffoldNodeIds || []).map((id) => id.replace(/^scaffold:/, "")));
  return `// ${SCREEN_SLOT_MARKER}: ${screen.screenId}.\n`
    + "// Model-owned visual/domain composition. This module is already mounted by the protected router.\n"
    + `// Journeys: ${owner.map((row) => row.journeyId).join(", ") || "none"}. Scaffold slots: ${families.join(", ") || "app_shell"}.\n`
    + `export default function ${String(screen.module).split("/").at(-1).replace(/\.(?:jsx?|tsx?)$/, "")}() {\n`
    + `  return <section data-scaffold-slot=${quote(screen.screenId)}><h1>${String(screen.routeName)}</h1><p>Application screen ready for composition.</p></section>;\n`
    + "}\n";
}

function manifestSource(graph) {
  return `${banner("machine manifest")}export const SCAFFOLD_COMPOSITION = Object.freeze(${js({
    version: SCAFFOLD_COMPOSITION_VERSION,
    graphVersion: graph?.version || 1,
    registryVersion: graph?.registryVersion || 1,
    families: (graph?.families || []).map((node) => ({ scaffoldId: node.scaffoldId, version: node.version })),
    routes: (graph?.routes || []).map((route) => ({ path: route.routePath, screenId: route.screenId,
      module: route.module, journeyIds: route.journeyIds || [] })),
    extensions: (graph?.extensions || []).map((extension) => ({ extensionId: extension.extensionId,
      module: extension.module, requiredExports: extension.requiredExports, owningJourneys: extension.owningJourneys })),
  })});
`;
}

export function renderScaffoldFoundation(graph) {
  const protectedFiles = {
    [SCAFFOLD_ENTRY_PATH]: `${banner("application entry shim")}export { default } from "./lib/scaffolds/composed/ScaffoldApp.jsx";\n`,
    [SCAFFOLD_PRIMITIVES_PATH]: primitivesSource(),
    [SCAFFOLD_APP_PATH]: scaffoldAppSource(graph),
    [SCAFFOLD_MANIFEST_PATH]: manifestSource(graph),
  };
  const screenFiles = Object.fromEntries((graph?.screens || []).map((screen) => [screen.module,
    screenSlotSource(screen, graph)]));
  return { protectedFiles, screenFiles };
}

export function scaffoldCompositionPlan(graph) {
  const rendered = renderScaffoldFoundation(graph);
  const protectedFiles = Object.keys(rendered.protectedFiles).sort();
  return {
    version: SCAFFOLD_COMPOSITION_VERSION,
    graphVersion: graph?.version || 1,
    registryVersion: graph?.registryVersion || 1,
    protectedRoot: SCAFFOLD_COMPOSED_ROOT,
    protectedFiles,
    protectedFileHashes: Object.fromEntries(protectedFiles.map((path) => [path, digest(rendered.protectedFiles[path])])),
    modelOwnedScreenFiles: Object.keys(rendered.screenFiles).sort(),
    routeScreenMap: (graph?.routes || []).map((route) => ({ routePath: route.routePath,
      screenId: route.screenId, module: route.module, journeyIds: route.journeyIds || [] })),
    extensionPoints: (graph?.extensions || []).map((extension) => ({ ...extension })),
    familyInterfaces: (graph?.families || []).map((node) => ({ scaffoldId: node.scaffoldId,
      version: node.version, extensionPoints: scaffoldEntry(node.scaffoldId)?.extensionPoints || [] })),
    expectedModuleSurface: graph?.expectedModuleSurface || null,
  };
}

/** Apply/refresh deterministic files. Existing model-owned screens are never overwritten. */
export function composeScaffoldFoundation(tree, graph) {
  const rendered = renderScaffoldFoundation(graph);
  const next = { ...(tree || {}), ...rendered.protectedFiles };
  for (const [path, source] of Object.entries(rendered.screenFiles)) {
    if (typeof next[path] !== "string") next[path] = source;
  }
  return { tree: next, plan: scaffoldCompositionPlan(graph), deterministicFilesCreated: Object.keys(rendered.protectedFiles),
    screenSlotsCreated: Object.keys(rendered.screenFiles).filter((path) => typeof tree?.[path] !== "string") };
}

function hasExport(source, name) {
  if (name === "default") return /\bexport\s+default\b/.test(source);
  return new RegExp(`\\bexport\\s+(?:async\\s+)?(?:function|class|const|let|var)\\s+${name}\\b`).test(source)
    || new RegExp(`\\bexport\\s*\\{[^}]*\\b${name}\\b`).test(source);
}

function isUnimplementedScreenSlot(source, screenId) {
  // The provenance comment intentionally survives replace_symbol patches. Placeholder detection
  // must follow the live render body, otherwise a fully implemented mounted screen is rejected
  // merely because the model preserved that useful ownership comment.
  return source.includes(`data-scaffold-slot=${quote(screenId)}`)
    && source.includes("Application screen ready for composition.");
}

export function validateScaffoldComposition(tree, graph, plan = scaffoldCompositionPlan(graph), {
  requireExtensions = true, rejectScreenSlots = false, journeyIds = null,
} = {}) {
  const problems = [];
  const selectedJourneys = journeyIds ? new Set(journeyIds) : null;
  for (const path of plan.protectedFiles || []) {
    if (typeof tree?.[path] !== "string") { problems.push(`protected scaffold module missing: ${path}`); continue; }
    const expected = plan.protectedFileHashes?.[path];
    if (expected && digest(tree[path]) !== expected) problems.push(`protected scaffold module modified: ${path}`);
  }
  for (const route of plan.routeScreenMap || []) {
    const source = tree?.[route.module];
    if (typeof source !== "string") problems.push(`mounted scaffold screen missing: ${route.module}`);
    else if (!hasExport(source, "default")) problems.push(`mounted scaffold screen must default export: ${route.module}`);
    else if (rejectScreenSlots && (!selectedJourneys
      || (route.journeyIds || []).some((id) => selectedJourneys.has(id)))
      && isUnimplementedScreenSlot(source, route.screenId)) problems.push(`mounted scaffold screen is still unimplemented: ${route.module}`);
    const router = String(tree?.[SCAFFOLD_APP_PATH] || "");
    if (!router.includes(JSON.stringify(route.routePath)) || !router.includes(route.module.split("/").at(-1).replace(/\.(?:jsx?|tsx?)$/, ""))) {
      problems.push(`route ${route.routePath} does not mount ${route.module}`);
    }
  }
  for (const owner of graph?.journeyOwnership || []) {
    const route = (plan.routeScreenMap || []).find((candidate) => candidate.screenId === owner.screenId);
    if (!route || route.module !== owner.mountedModule || !route.journeyIds.includes(owner.journeyId)) {
      problems.push(`journey ${owner.journeyId} is not traceable to its mounted live screen`);
    }
  }
  if (requireExtensions) {
    for (const extension of plan.extensionPoints || []) {
      if (selectedJourneys && !(extension.owningJourneys || []).some((id) => selectedJourneys.has(id))) continue;
      const source = tree?.[extension.module];
      if (typeof source !== "string") { problems.push(`custom extension missing: ${extension.module}`); continue; }
      for (const name of extension.requiredExports || []) {
        if (!hasExport(source, name)) problems.push(`${extension.module} must export ${name}`);
      }
    }
  }
  return { ok: problems.length === 0, problems };
}

export function scaffoldCompositionBrief(graph, plan = scaffoldCompositionPlan(graph)) {
  return [
    "DETERMINISTIC SCAFFOLD COMPOSITION (mounted runtime authority; consume, never regenerate):",
    JSON.stringify({ version: plan.version, families: plan.familyInterfaces,
      mountedRoutes: plan.routeScreenMap, protectedFiles: plan.protectedFiles,
      customExtensions: plan.extensionPoints.map((extension) => ({ extensionId: extension.extensionId,
        owningJourneys: extension.owningJourneys, inputs: extension.inputs, outputs: extension.outputs,
        reads: extension.reads, writes: extension.writes, allowedFiles: extension.allowedFiles,
        requiredExports: extension.requiredExports, integrationPoints: extension.integrationPoints,
        operationContracts: extension.operationContracts,
        verificationSemantics: extension.verificationSemantics })) }, null, 2),
    "The protected router already mounts every screen above. Implement visual/domain composition inside",
    "those existing screen slots and only the declared custom extension files. Do not write App.jsx,",
    "the composed scaffold root, a competing router, or a free-form replacement application shell.",
    "Select each custom-extension operation with a literal second-argument context such as",
    "{ operation: \"<operationId>\" }. The explicit legacy key operationId is also supported.",
    "At every custom-extension call site, pass the selected operation's declared inputKeys as explicit",
    "object properties. An object spread is not proof that a differently named domain field satisfies the interface.",
  ].join("\n");
}
